# Generated by Django 5.2 on 2025-05-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='protocols/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='medical_care.emergencycondition')),
            ],
            options={
                'verbose_name': 'Медиа-материал',
                'verbose_name_plural': 'Медиа-материалы',
                'ordering': ['order'],
            },
        ),
    ]
